:DOC-CONFIG:
#+PROPERTY: header-args:conf :tangle hyprland.conf :comments link
#+auto_tangle: t
:END:

#+TITLE: hyprland config
#+AUTHOR: Dak

This is my hyprland config

* Main
** Source
 Sourcing external config files
 #+begin_src example
# [[file:hyprland.org::*Input][Input:1]]
# Input:1 ends here
#+end_src

* Startup Apps
Commands & Apps that will be executed when hyprland starts

** First to be run

#+begin_src conf
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh
#+end_src

** wallpaper stuff / More wallpaper options below

#+begin_src conf
exec-once = swww-daemon --format xrgb
#+end_src

for random wallpaper switcher every 30 minutes add this line to above src block:
exec-once = $SwwwRandom $wallDIR

** Startup

#+begin_src conf
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#+end_src

** Polkit (Polkit Gnome / KDE)

#+begin_src conf
exec-once = $scriptsDir/Polkit.sh
#+end_src

** startup apps

#+begin_src conf

exec-once = waybar &
exec-once = nm-applet --indicator &
exec-once = swaync &
exec-once = ags &
#exec-once = blueman-applet &
#exec-once = rog-control-center &
#+end_src

** clipboard manager

#+begin_src conf
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
#+end_src

** Starting hypridle to start hyprlock

#+begin_src conf
exec-once = hypridle &
#+end_src

** Start pyprland daemon
#+begin_src conf
exec-once = pypr &
#+end_src

** Here are list of features available but disabled by default

Add any to a src block to use

exec-once = swww-daemon --format xrgb && swww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

gnome polkit for nixos
exec-once = $scriptsDir/Polkit-NixOS.sh

xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
exec-once = $scriptsDir/PortalHyprland.sh

* Settings

Default Settings. avoid changing this file as during update, this will be replaced
refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables
Initial boot script enable to apply initial wallpapers, theming, new settings etc

#+begin_src conf
exec-once = $HOME/.config/hypr/initial-boot.sh
#+end_src


* Keybinds
Main Keybinds

#+begin_src conf
$mainMod = SUPER
#+end_src

** Default

#+begin_src conf
$scriptsDir = $HOME/.config/hypr/scripts
$configs = $HOME/.config/hypr/configs
#+end_src

** User

#+begin_src conf
$UserConfigs = $HOME/.config/hypr/UserConfigs
$UserScripts = $HOME/.config/hypr/UserScripts

bind = CTRL ALT, Delete, exec, hyprctl dispatch exit 0
bind = $mainMod, Q, killactive,
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, Q, exec, $scriptsDir/KillActiveProcess.sh
bind = $mainMod SHIFT, F, togglefloating,
bind = $mainMod ALT, F, exec, hyprctl dispatch workspaceopt allfloat
bind = CTRL ALT, L, exec, $scriptsDir/LockScreen.sh
bind = CTRL ALT, P, exec, $scriptsDir/Wlogout.sh
#+end_src

** FEATURES / EXTRAS

#+begin_src conf
bind = $mainMod, H, exec, $scriptsDir/KeyHints.sh # Small help file
bind = $mainMod ALT, R, exec, $scriptsDir/Refresh.sh # Refresh waybar, swaync, rofi
bind = $mainMod ALT, E, exec, $scriptsDir/RofiEmoji.sh # emoji
#bind = $mainMod, S, exec, $scriptsDir/RofiSearch.sh # Google search from Rofi
bind = $mainMod SHIFT, B, exec, $scriptsDir/ChangeBlur.sh # Toggle blur settings
bind = $mainMod SHIFT, G, exec, $scriptsDir/GameMode.sh # animations ON/OFF
bind = $mainMod ALT, L, exec, $scriptsDir/ChangeLayout.sh # Toggle Master or Dwindle Layout
bind = $mainMod ALT, V, exec, $scriptsDir/ClipManager.sh # Clipboard Manager
bind = $mainMod SHIFT, N, exec, swaync-client -t -sw # swayNC panel
#+end_src

** FEATURES / EXTRAS (UserScripts)

#+begin_src conf
bind = $mainMod, L, exec, $UserScripts/QuickEdit.sh # Quick Edit Hyprland Settings
bind = $mainMod SHIFT, M, exec, $UserScripts/RofiBeats.sh # online music
bind = $mainMod, W, exec, $UserScripts/WallpaperSelect.sh # Select wallpaper to apply
bind = $mainMod SHIFT, W, exec, $UserScripts/WallpaperEffects.sh # Wallpaper Effects by imagemagickWW
bind = CTRL ALT, W, exec, $UserScripts/WallpaperRandom.sh # Random wallpapers
bind = $mainMod ALT, O, exec, hyprctl setprop active opaque toggle #disable opacity to active window
bind = $mainMod SHIFT, K, exec, $scriptsDir/KeyBinds.sh # searchable keybinds
# Waybar / Bar related
bind = $mainMod, B, exec, pkill -SIGUSR1 waybar # Toggle hide/show waybar
#+end_src

** Dwindle Layout

#+begin_src conf
bind = $mainMod SHIFT, I, togglesplit # only works on dwindle layout
bind = $mainMod, P, pseudo, # dwindle
#+end_src

** Master Layout

#+begin_src conf
bind = $mainMod CTRL, D, layoutmsg, removemaster
bind = $mainMod, U, layoutmsg, addmaster
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, K, layoutmsg, cycleprev
bind = $mainMod CTRL, Return, layoutmsg, swapwithmaster
#+end_src

** Works on either layout (Master or Dwindle)

#+begin_src conf
bind = $mainMod, M, exec, hyprctl dispatch splitratio 0.3
#+end_src

** group

#+begin_src conf
bind = $mainMod, G, togglegroup
bind = $mainMod CTRL, tab, changegroupactive  #change focus to another window
#+end_src

** Cycle windows if floating bring to top

#+begin_src conf
bind = ALT, tab, cyclenext
bind = ALT, tab, bringactivetotop
#+end_src

** Special Keys / Hot Keys

#+begin_src conf
bindel = , xf86audioraisevolume, exec, $scriptsDir/Volume.sh --inc #volume up
bindel = , xf86audiolowervolume, exec, $scriptsDir/Volume.sh --dec #volume down
bindl = , xf86AudioMicMute, exec, $scriptsDir/Volume.sh --toggle-mic #mute mic
bindl = , xf86audiomute, exec, $scriptsDir/Volume.sh --toggle
bindl = , xf86Sleep, exec, systemctl suspend  # sleep button
bindl = , xf86Rfkill, exec, $scriptsDir/AirplaneMode.sh #Airplane mode

#+end_src
** media controls using keyboards

#+begin_src conf
bindl = , xf86AudioPlayPause, exec, $scriptsDir/MediaCtrl.sh --pause
bindl = , xf86AudioPause, exec, $scriptsDir/MediaCtrl.sh --pause
bindl = , xf86AudioPlay, exec, $scriptsDir/MediaCtrl.sh --pause
bindl = , xf86AudioNext, exec, $scriptsDir/MediaCtrl.sh --nxt
bindl = , xf86AudioPrev, exec, $scriptsDir/MediaCtrl.sh --prv
bindl = , xf86audiostop, exec, $scriptsDir/MediaCtrl.sh --stop
#+end_src

** Screenshot keybindings NOTE: You may need to press Fn key as well

#+begin_src conf
bind = $mainMod, Print, exec, $scriptsDir/ScreenShot.sh --now
bind = $mainMod SHIFT, Print, exec, $scriptsDir/ScreenShot.sh --area
bind = $mainMod CTRL, Print, exec, $scriptsDir/ScreenShot.sh --in5 #screenshot in 5 secs
bind = $mainMod CTRL SHIFT, Print, exec, $scriptsDir/ScreenShot.sh --in10 #screenshot in 10 secs
bind = ALT, Print, exec, $scriptsDir/ScreenShot.sh --active #take screenshot of active window
#+end_src

** screenshot with swappy (another screenshot tool)

#+begin_src conf
bind = $mainMod SHIFT, S, exec, $scriptsDir/ScreenShot.sh --swappy
#+end_src

** Resize windows

#+begin_src conf
binde = $mainMod SHIFT, left, resizeactive,-50 0
binde = $mainMod SHIFT, right, resizeactive,50 0
binde = $mainMod SHIFT, up, resizeactive,0 -50
binde = $mainMod SHIFT, down, resizeactive,0 50
#+end_src

** Move windows

#+begin_src conf
bind = $mainMod CTRL, left, movewindow, l
bind = $mainMod CTRL, right, movewindow, r
bind = $mainMod CTRL, up, movewindow, u
bind = $mainMod CTRL, down, movewindow, d
#+end_src

** Move focus with mainMod + arrow keys

#+begin_src conf
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
#+end_src

** Workspaces related

#+begin_src conf
bind = $mainMod, tab, workspace, m+1
bind = $mainMod SHIFT, tab, workspace, m-1
#+end_src

** Special workspace
#+begin_src conf
bind = $mainMod SHIFT, U, movetoworkspace, special
bind = $mainMod, U, togglespecialworkspace,
#+end_src

** The following mappings use the key codes to better support various keyboard layouts

1 is code:10, 2 is code 11, etc
Switch workspaces with mainMod + [0-9]

#+begin_src conf
bind = $mainMod, code:10, workspace, 1
bind = $mainMod, code:11, workspace, 2
bind = $mainMod, code:12, workspace, 3
bind = $mainMod, code:13, workspace, 4
bind = $mainMod, code:14, workspace, 5
bind = $mainMod, code:15, workspace, 6
bind = $mainMod, code:16, workspace, 7
bind = $mainMod, code:17, workspace, 8
bind = $mainMod, code:18, workspace, 9
bind = $mainMod, code:19, workspace, 10
#+end_src

** Move active window and follow to workspace mainMod + SHIFT [0-9]

#+begin_src conf
bind = $mainMod SHIFT, code:10, movetoworkspace, 1
bind = $mainMod SHIFT, code:11, movetoworkspace, 2
bind = $mainMod SHIFT, code:12, movetoworkspace, 3
bind = $mainMod SHIFT, code:13, movetoworkspace, 4
bind = $mainMod SHIFT, code:14, movetoworkspace, 5
bind = $mainMod SHIFT, code:15, movetoworkspace, 6
bind = $mainMod SHIFT, code:16, movetoworkspace, 7
bind = $mainMod SHIFT, code:17, movetoworkspace, 8
bind = $mainMod SHIFT, code:18, movetoworkspace, 9
bind = $mainMod SHIFT, code:19, movetoworkspace, 10
bind = $mainMod SHIFT, bracketleft, movetoworkspace, -1 # brackets [ or ]
bind = $mainMod SHIFT, bracketright, movetoworkspace, +1
#+end_src

** Move active window to a workspace silently mainMod + CTRL [0-9]

#+begin_src conf
bind = $mainMod CTRL, code:10, movetoworkspacesilent, 1
bind = $mainMod CTRL, code:11, movetoworkspacesilent, 2
bind = $mainMod CTRL, code:12, movetoworkspacesilent, 3
bind = $mainMod CTRL, code:13, movetoworkspacesilent, 4
bind = $mainMod CTRL, code:14, movetoworkspacesilent, 5
bind = $mainMod CTRL, code:15, movetoworkspacesilent, 6
bind = $mainMod CTRL, code:16, movetoworkspacesilent, 7
bind = $mainMod CTRL, code:17, movetoworkspacesilent, 8
bind = $mainMod CTRL, code:18, movetoworkspacesilent, 9
bind = $mainMod CTRL, code:19, movetoworkspacesilent, 10
bind = $mainMod CTRL, bracketleft, movetoworkspacesilent, -1 # brackets [ or ]
bind = $mainMod CTRL, bracketright, movetoworkspacesilent, +1
#+end_src

** Scroll through existing workspaces with mainMod + scroll
#+begin_src conf
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, period, workspace, e+1
bind = $mainMod, comma, workspace, e-1
#+end_src

** Move/resize windows with mainMod + LMB/RMB and dragging

#+begin_src conf
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
#+end_src


* ENVariables
** Environment Variables
Set your defaults here

subl = sublime-text
emacs = emacs

#+begin_src conf
env = EDITOR,emacs #default editor
#+end_src

environment-variables
#+begin_src conf
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
#+end_src

** xwayland apps scale fix
toolkit-specific scale
#+begin_src conf
env = GDK_SCALE,1
#+end_src

firefox
#+begin_src conf
env = MOZ_ENABLE_WAYLAND,1
#+end_src

electron >28 apps (may help)
#+begin_src conf
env = ELECTRON_OZONE_PLATFORM_HINT,auto
#+end_src

** other envariables
NVIDIA
This is from Hyprland Wiki. Below will be activated nvidia gpu detected
See hyprland wiki https://wiki.hyprland.org/Nvidia/#environment-variables
#env = LIBVA_DRIVER_NAME,nvidia
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia
#env = NVD_BACKEND,direct

additional ENV's for nvidia. Caution, activate with care
#env = GBM_BACKEND,nvidia-drm

#env = __NV_PRIME_RENDER_OFFLOAD,1
#env = __VK_LAYER_NV_optimus,NVIDIA_only
#env = WLR_DRM_NO_ATOMIC,1

FOR VM and POSSIBLY NVIDIA
LIBGL_ALWAYS_SOFTWARE software mesa rendering
#env = LIBGL_ALWAYS_SOFTWARE,1
#env = WLR_RENDERER_ALLOW_SOFTWARE,1

nvidia firefox (for hardware acceleration on FF)?
check this post https://github.com/elFarto/nvidia-vaapi-driver#configuration
#env = MOZ_DISABLE_RDD_SANDBOX,1
#env = EGL_PLATFORM,wayland



* Laptops
For laptops

#+begin_src conf
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs
#+end_src

** Touchpad
for disabling Touchpad. hyprctl devices to get device name.

#+begin_src conf
$Touchpad_Device=asue1209:00-04f3:319f-touchpad

$TOUCHPAD_ENABLED = true
device {
  name = $Touchpad_Device
  enabled = $TOUCHPAD_ENABLED
}
#+end_src


** Bind
#+begin_src conf
binde = , xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec #Keyboard brightness Down
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc #Keyboard brightness up
bind = , xf86Launch1, exec, rog-control-center # ASUS Armory crate button
bind = , xf86Launch3, exec, asusctl led-mode -n #FN+F4 Switch keyboard RGB profile
bind = , xf86Launch4, exec, asusctl profile -n  #FN+F5 change of fan profiles (Quite, Balance, Performance)
binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc
bind = , xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh #disable touchpad

# Screenshot keybindings for Asus G15 (no PrinSrc button)
bind = $mainMod, F6, exec, $scriptsDir/ScreenShot.sh --now # Fullscreen
bind = $mainMod SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area
bind = $mainMod CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5 # Screenshot in 5 secs
bind = $mainMod ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10 # Screenshot in 10 secs
bind = ALT, F6, exec, $scriptsDir/ScreenShot.sh --active # Screenshot active window
#+end_src

** Other laptop
Below are useful when you are connecting your laptop in external display
Suggest you edit below for your laptop display
From WIKI This is to disable laptop monitor when lid is closed.
consult https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Binds/#switches

bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, auto, 1"
bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"


WARNING! Using this method has some caveats!! USE THIS PART WITH SOME CAUTION!
CONS of doing this, is that you need to set up your wallpaper (SUPER W) and choose wallpaper.
CAVEATS! Sometimes the Main Laptop Monitor DOES NOT have display that it needs to re-connect your external monitor
One work around is to ensure that before shutting down laptop, MAKE SURE your laptop lid is OPEN!!
Make sure to comment (put # on the both the bindl = , switch ......) above
NOTE: Display for laptop are being generated into LaptopDisplay.conf
This part is to be use if you do not want your main laptop monitor to wake up during say wallpaper change etc

bindl = , switch:off:Lid Switch,exec,echo "monitor = eDP-1, preferred, auto, 1" > $UserConfigs/LaptopDisplay.conf
bindl = , switch:on:Lid Switch,exec,echo "monitor = eDP-1, disable" > $UserConfigs/LaptopDisplay.conf

for laptop-lid action (to erase the last entry)

exec-once = echo "monitor = eDP-1, preferred, auto, 1" > $HOME/.config/hypr/UserConfigs/LaptopDisplay.conf


* Monitors
** Monitor 1
Monitor Configuration
See Hyprland wiki for more details
https://wiki.hyprland.org/Configuring/Monitors/
Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

#+begin_src conf


# Monitors
monitor=,preferred,auto,1
#+end_src

# NOTE: for laptop, kindly check notes in Laptops.conf regarding display
# Created this inorder for the monitor display to not wake up if not intended.
# See here: https://github.com/hyprwm/Hyprland/issues/4090

# Some examples
#monitor = eDP-1, preferred, auto, 1
#monitor = eDP-1, 2560x1440@165, 0x0, 1 #own screen
#monitor = DP-3, 1920x1080@240, auto, 1
#monitor = DP-1, preferred, auto, 1
#monitor = HDMI-A-1, preferred,auto,1

# QEMU-KVM, virtual box or vmware
#monitor = Virtual-1, 1920x1080@60,auto,1

# High Refresh Rate
#monitor=,highrr,auto,1

# High Resolution
#monitor=,highres,auto,1

# to disable a monitor
#monitor=name,disable

# Mirror samples
#monitor=DP-3,1920x1080@60,0x0,1,mirror,DP-2
#monitor=,preferred,auto,1,mirror,eDP-1
#monitor=HDMI-A-1,2560x1440@144,0x0,1,mirror,eDP-1

# 10 bit monitor support - See wiki https://wiki.hyprland.org/Configuring/Monitors/#10-bit-support - See NOTES below
# NOTE: Colors registered in Hyprland (e.g. the border color) do not support 10 bit.
# NOTE: Some applications do not support screen capture with 10 bit enabled. (Screen captures like OBS may render black screen)
monitor=,preferred,auto,1,bitdepth,10

monitor=eDP-1,transform,0
monitor=eDP-1,addreserved,10,10,10,49

workspaces - Monitor rules
https://wiki.hyprland.org/Configuring/Workspace-Rules/
SUPER E - Workspace-Rules
See ~/.config/hypr/UserConfigs/WorkspaceRules.conf


* Laptop Display only
only use if its not working by default
NOTE, THIS FILE IS BEING USED by disabling Laptop display monitor behaviour when closing lid.
See notes on Laptops.conf

monitor = eDP-1, preferred, auto, 1



* Window Rules


#windowrule = noblur,gamescope
#windowrule = fullscreen,gamescope
#windowrule = workspace 6 silent,^(gamescope)$

** windowrule Position

#+begin_src conf
windowrule = center,^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)
windowrule = center,^([Ww]hatsapp-for-linux)$
windowrule = center,^([Ff]erdium)$
#+end_src


** WINDOWRULE v2

windowrule v2 - position
windowrulev2 = center,floating:1 # warning, it cause even the menu to float and center.

#+begin_src conf
windowrulev2 = center, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = center, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = center, title:^(ROG Control)$
windowrulev2 = center, title:^(Keybindings)$
windowrulev2 = move 72% 7%,title:^(Picture-in-Picture)$
#windowrulev2 = move 72% 7%,title:^(Firefox)$

# windowrule v2 to avoid idle for fullscreen apps
windowrulev2 = idleinhibit fullscreen, class:^(*)$
windowrulev2 = idleinhibit fullscreen, title:^(*)$
windowrulev2 = idleinhibit fullscreen, fullscreen:1
#+end_src

** windowrule v2 move to workspace

#+begin_src conf
windowrulev2 = workspace 1, class:^([Tt]hunderbird)$
windowrulev2 = workspace 2, class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$
windowrulev2 = workspace 2, class:^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable)?)$
windowrulev2 = workspace 2, class:^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$
windowrulev2 = workspace 2, class:^([Tt]horium-browser)$
windowrulev2 = workspace 3, class:^([Tt]hunar)$
windowrulev2 = workspace 4, class:^(com.obsproject.Studio)$
windowrulev2 = workspace 5, class:^([Ss]team)$
windowrulev2 = workspace 5, class:^([Ll]utris)$
windowrulev2 = workspace 7, class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$
windowrulev2 = workspace 7, class:^([Ff]erdium)$
windowrulev2 = workspace 7, class:^([Ww]hatsapp-for-linux)$
windowrulev2 = workspace 1, class:(kitty)$

# windowrule v2 move to workspace (silent)
windowrulev2 = workspace 6 silent, class:^(virt-manager)$
windowrulev2 = workspace 9 silent, class:^([Aa]udacious)$
#+end_src

** windowrule v2 - float

#+begin_src conf
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float, class:([Zz]oom|onedriver|onedriver-launcher)$
windowrulev2 = float, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:(org.gnome.Calculator), title:(Calculator)
windowrulev2 = float, class:(codium|codium-url-handler|VSCodium|code-oss), title:(Add Folder to Workspace)
windowrulev2 = float, class:(electron), title:(Add Folder to Workspace)
windowrulev2 = float, class:^([Rr]ofi)$
windowrulev2 = float, class:^(eog|org.gnome.Loupe)$ # image viewer
windowrulev2 = float, class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$
windowrulev2 = float, class:^(nwg-look|qt5ct|qt6ct)$
windowrulev2 = float, class:^(mpv|com.github.rafostar.Clapper)$
windowrulev2 = float, class:^(nm-applet|nm-connection-editor|blueman-manager)$
windowrulev2 = float, class:^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$ # system monitor
windowrulev2 = float, class:^([Yy]ad)$
windowrulev2 = float, class:^(wihotspot(-gui)?)$ # wifi hotspot
windowrulev2 = float, class:^(evince)$ # document viewer
windowrulev2 = float, class:^(file-roller|org.gnome.FileRoller)$ # archive manager
windowrulev2 = float, class:^([Bb]aobab|org.gnome.[Bb]aobab)$ # Disk usage analyzer
windowrulev2 = float, title:(Kvantum Manager)
windowrulev2 = float, class:^([Ss]team)$,title:^((?![Ss]team).*|[Ss]team [Ss]ettings)$
windowrulev2 = float, class:^([Qq]alculate-gtk)$
#windowrulev2 = float, class:^([Ww]hatsapp-for-linux)$
windowrulev2 = float, class:^([Ff]erdium)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(ROG Control)$
#windowrulev2 = float, title:^(Firefox)$
#+end_src

** windowrule v2 - opacity #enable as desired

#+begin_src conf
windowrulev2 = opacity 0.9 0.6, class:^([Rr]ofi)$
windowrulev2 = opacity 0.9 0.7, class:^(Brave-browser(-beta|-dev)?)$
windowrulev2 = opacity 0.9 0.7, class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$
windowrulev2 = opacity 0.9 0.7, class:^(zen-alpha)$ # zen browser
windowrulev2 = opacity 0.9 0.6, class:^([Tt]horium-browser)$
windowrulev2 = opacity 0.9 0.8, class:^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable)?)$
windowrulev2 = opacity 0.9 0.8, class:^(google-chrome(-beta|-dev|-unstable)?)$
windowrulev2 = opacity 0.94 0.86, class:^(chrome-.+-Default)$ # Chrome PWAs
windowrulev2 = opacity 0.9 0.8, class:^([Tt]hunar|org.gnome.Nautilus)$
windowrulev2 = opacity 0.8 0.6, class:^(pcmanfm-qt)$
windowrulev2 = opacity 0.8 0.7, class:^(gedit|org.gnome.TextEditor|mousepad)$
windowrulev2 = opacity 0.9 0.8, class:^(deluge)$
windowrulev2 = opacity 0.8 0.7, class:^(Alacritty|kitty|kitty-dropterm)$ # Terminals
windowrulev2 = opacity 0.9 0.7, class:^(VSCodium|codium-url-handler|code-oss)$
windowrulev2 = opacity 0.9 0.8, class:^(nwg-look|qt5ct|qt6ct|[Yy]ad)$
windowrulev2 = opacity 0.9 0.8, title:(Kvantum Manager)
windowrulev2 = opacity 0.9 0.7, class:^(com.obsproject.Studio)$
windowrulev2 = opacity 0.9 0.7, class:^([Aa]udacious)$
windowrulev2 = opacity 0.9 0.8, class:^(VSCode|code-url-handler)$
windowrulev2 = opacity 0.9 0.8, class:^(jetbrains-.+)$ # JetBrains IDEs
windowrulev2 = opacity 0.94 0.86, class:^([Dd]iscord|[Vv]esktop)$
windowrulev2 = opacity 0.9 0.8, class:^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$
windowrulev2 = opacity 0.9 0.8, class:^(im.riot.Riot)$ # Element matrix client
windowrulev2 = opacity 0.94 0.86, class:^(gnome-disks|evince|wihotspot(-gui)?|org.gnome.baobab)$
windowrulev2 = opacity 0.9 0.8, class:^(file-roller|org.gnome.FileRoller)$ # archive manager
windowrulev2 = opacity 0.8 0.7, class:^(app.drey.Warp)$ # Warp file transfer
windowrulev2 = opacity 0.9 0.8, class:^(seahorse)$ # gnome-keyring gui
windowrulev2 = opacity 0.82 0.75, class:^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$
windowrulev2 = opacity 0.9 0.8, class:^(xdg-desktop-portal-gtk)$ # gnome-keyring gui
windowrulev2 = opacity 0.9 0.7, class:^([Ww]hatsapp-for-linux)$
windowrulev2 = opacity 0.9 0.7, class:^([Ff]erdium)$
windowrulev2 = opacity 0.95 0.75, title:^(Picture-in-Picture)$
#+end_src

** windowrule v2 - size

#+begin_src conf
windowrulev2 = size 70% 70%, class:^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$
windowrulev2 = size 70% 70%, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = size 60% 70%, title:(Kvantum Manager)
windowrulev2 = size 60% 70%, class:^(qt6ct)$
windowrulev2 = size 70% 70%, class:^(evince|wihotspot(-gui)?)$
windowrulev2 = size 60% 70%, class:^(file-roller|org.gnome.FileRoller)$
windowrulev2 = size 60% 70%, class:^([Ww]hatsapp-for-linux)$
windowrulev2 = size 60% 70%, class:^([Ff]erdium)$
windowrulev2 = size 60% 70%, title:^(ROG Control)$
#windowrulev2 = size 25% 25%, title:^(Picture-in-Picture)$
#windowrulev2 = size 25% 25%, title:^(Firefox)$
#+end_src

** windowrule v2 - pinning

#+begin_src
windowrulev2 = pin,title:^(Picture-in-Picture)$
#windowrulev2 = pin,title:^(Firefox)$
#+end_src

** windowrule v2 - extras

#+begin_src conf
windowrulev2 = keepaspectratio, title:^(Picture-in-Picture)$

#windowrulev2 = bordercolor rgb(EE4B55) rgb(880808), fullscreen:1
#windowrulev2 = bordercolor rgb(282737) rgb(1E1D2D), floating:1
#windowrulev2 = opacity 0.8 0.8, pinned:1


# LAYER RULES
#layerrule = unset,class:^([Rr]ofi)$
#layerrule = blur,class:^([Rr]ofi)$
#layerrule = ignorezero, <rofi>

#layerrule = ignorezero, overview
#layerrule = blur, overview
#+end_src


* User Decor Animations
Decoration and animaiton settings

** Hyprland Wiki Links
Animation - https://wiki.hyprland.org/Configuring/Animations/
Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

** Sourcing colors generated by wallust

#+begin_src conf
source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
#+end_src

** Decoration

#+begin_src conf
decoration {
  rounding = 10

  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.1
  dim_special = 0.8

  drop_shadow = true
  shadow_range = 6
  shadow_render_power = 1

  col.shadow = $foreground
  col.shadow_inactive = 0x50000000

  blur {
    enabled = true
    size = 6
    passes = 2
    ignore_opacity = true
    new_optimizations = true
    special = true
  }
}
#+end_src


** Animations

#+begin_src conf
animations {
  enabled = yes

  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1
  bezier = overshot, 0.05, 0.9, 0.1, 1.05
  bezier = smoothOut, 0.5, 0, 0.99, 0.99
  bezier = smoothIn, 0.5, -0.5, 0.68, 1.5

  animation = windows, 1, 6, wind, slide
  animation = windowsIn, 1, 5, winIn, slide
  animation = windowsOut, 1, 3, smoothOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = fade, 1, 3, smoothOut
  animation = workspaces, 1, 5, overshot

  # animations for -git or version >0.42.0
  animation = workspacesIn, 1, 5, winIn, slide
  animation = workspacesOut, 1, 5, winOut, slide
}
#+end_src

* User Keybinds

This is where you put your own keybinds. Be Mindful to check as well [[Keybinds]] to make sure they dont conflict

# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds
** Main user keybinds
#+begin_src conf
$mainMod = SUPER
$files = thunar
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
#+end_src

** rofi App launcher

#+begin_src conf
#bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
bind = $mainMod, R, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window
bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview'
#+end_src

** terminal, file manager, browser keys

#+begin_src conf
bind = $mainMod, Return, exec, $term  # Launch terminal
bind = $mainMod, E, exec, $files # Launch file

bind = $mainMod, I, exec, firefox # Launch Firefox
bind = $mainMod, S, exec, subl # Launch sublime change later to emacs



bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)
#+end_src

** pyprland

#+begin_src conf
bind = $mainMod SHIFT, Return, exec, pypr toggle term # Dropdown terminal
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom
#+end_src

** Other

#+begin_src conf
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh # Changing the keyboard layout
#+end_src

** VM Passthrough

For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

* User Settings
This is where you put your own settings as this will not be touched during update
if the upgrade.sh is used.

refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

** Sourcing colors generated by wallust

#+begin_src conf
source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
#+end_src

#+begin_src conf
dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_status = master
  new_on_top = 1
  mfact = 0.5
}

general {
  border_size = 2
  gaps_in = 6
  gaps_out = 8

  resize_on_border = true

  col.active_border = $color0
  col.inactive_border = $backgroundCol

  layout = dwindle
}
#+end_src

** Input

#+begin_src conf
input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300

  sensitivity = 0 #mouse sensitivity
  numlock_by_default = true
  left_handed = false
  follow_mouse = true
  float_switch_override_focus = false

  touchpad {
    disable_while_typing = true
    natural_scroll = true
    clickfinger_behavior = false
    middle_button_emulation = true
    tap-to-click = true
    drag_lock = false
          }

  # below for devices with touchdevice ie. touchscreen
	touchdevice {
		enabled = true
	}

	# below is for table see link above for proper variables
	tablet {
		transform = 0
		left_handed = 0
	}
}
#+end_src

** Gestures

#+begin_src conf
gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true
  #workspace_swipe_use_r = true #uncomment if wanted a forever create a new workspace with swipe right
}


group {
  col.border_active = $color1

	groupbar {
		col.active = $color0
  }
}
#+end_src

** Misc

#+begin_src conf
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  #vrr = 0
  mouse_move_enables_dpms = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
  focus_on_activate = false
  #no_direct_scanout = true #for fullscreen games - deprecated
  initial_workspace_tracking = 0
  middle_click_paste = false
}

#opengl {
#  nvidia_anti_flicker = true
#}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

#Could help when scaling and not pixelating
xwayland {
  force_zero_scaling = true
}

# render section for Hyprland >= v0.42.0
render {
  explicit_sync = 2
  explicit_sync_kms = 2
  direct_scanout = false
}

cursor {
  no_hardware_cursors = false
  enable_hyprcursor = true
  warp_on_change_workspace = true
  no_warps = true
}
#+end_src


* Workspace Rules

None of these are active at the moment add what you need to a src block

You can set workspace rules to achieve workspace-specific behaviors.
For instance, you can define a workspace where all windows are drawn without borders or gaps.

# https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Assigning workspace to a certain monitor. Below are just examples
# workspace = 1, monitor:eDP-1
# workspace = 2, monitor:eDP-1
# workspace = 3, monitor:eDP-1
# workspace = 4, monitor:eDP-1
# workspace = 5, monitor:DP-2
# workspace = 6, monitor:DP-2
# workspace = 7, monitor:DP-2
# workspace = 8, monitor:DP-2


# example rules (from wiki)
# workspace = 3, rounding:false, decorate:false
# workspace = name:coding, rounding:false, decorate:false, gapsin:0, gapsout:0, border:false, decorate:false, monitor:DP-1
# workspace = 8,bordersize:8
# workspace = name:Hello, monitor:DP-1, default:true
# workspace = name:gaming, monitor:desc:Chimei Innolux Corporation 0x150C, default:true
# workspace = 5, on-created-empty:[float] firefox
# workspace = special:scratchpad, on-created-empty:foot


* About
        Use this .org to make future conf files about hyprland. make sure to change doc-config


* Sources
These are the sources that I learned from.

I started with JaKooLits install sctipt and changed it to my needs. I took and simplified and made it a .org file.
but full credit to JaKooLit for the install script and start to all the configs. Some of the comments are mine some are JaKooLit
---- 💫 https://github.com/JaKooLit 💫 ----
